resolver: lts-13.21

extra-deps:
- happy-1.19.12
- shake-0.18.3@sha256:12949a47f07915a4338291a0146158d18abdd04c0dfd813778231ed68b4758df,14806

packages:
- '.'
- '../libraries/Cabal/Cabal'

nix:
   enable: false
   packages:
   - autoconf
   - automake
   - gcc
   - git
   - ncurses
   - perl
