/* -----------------------------------------------------------------------------
 *
 * (c) The GHC Team, 2008-2009
 *
 * Initialization of the Static Pointer Table
 *
 * Do not #include this file directly: #include "Rts.h" instead.
 *
 * To understand the structure of the RTS headers, see the wiki:
 *   http://ghc.haskell.org/trac/ghc/wiki/Commentary/SourceTree/Includes
 *
 * -------------------------------------------------------------------------- */

#ifndef RTS_SPT_H
#define RTS_SPT_H

/** Adds the given definitions to the SPT.
 *
 * The entries in the array are grouped in pairs. The first component contains
 * a key (StgWord64[2]) and the second component contains a pointer to the
 * closure defining the table entry (GHC.SptEntry).
 *
 * This function is called from the code generated by
 * compiler/deSugar/SPT.sptInitCode
 *
 * */
void hs_spt_module_init (void * entries[]);

#endif /* RTS_HPC_H */
